FashionGo - full - Copy/FashionGo/Controllers/BlogsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionGo.Controllers
{
    public class BlogsController : BaseController
    {
        
        // GET: Blogs
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            var pageSize = 8;
            var model = db.Posts.Where(p => p.Active == true).OrderByDescending(p => p.createDate).ToList();
            return View(model.ToPagedList(pageNumber, pageSize));
        }
        

        // GET: Category
        public ActionResult Category(string Slug, int? page)
        {
            int pageNumber = (page ?? 1);
            var pageSize = 8;

            var Cat = db.Categories.SingleOrDefault(c => c.Slug == Slug);
            if (Cat == null)
            {
                return RedirectToRoute("404");
            }

            var model = Cat.Posts.OrderByDescending(p => p.createDate).Where(p => p.Active == true).ToList();
            ViewBag.Cat = Cat;
            return View(model.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult ShowPost(string Slug)
        {
            var Post = db.Posts.SingleOrDefault(p => p.Slug == Slug);

            if (Post == null)
            {
                return RedirectToRoute("404");
            }

            ViewBag.RelatedPosts = db.Posts.Where(p => p.CatId == Post.CatId).Where(p => p.Id != Post.Id).Take(4).ToList();
            ViewBag.Cat = Post.Category;

            return View(Post);
        }

        //get siderbar
        public ActionResult _Sidebar()
        {
            ViewBag.Cats = db.Categories.ToList();
            var PopularPosts = db.Posts.OrderByDescending(p => p.createDate).Where(p => p.Active == true).Take(5);
            return PartialView(PopularPosts);
        }

        public ActionResult _LastNews()
        {
            var model = db.Posts.Where(p => p.Active == true).OrderByDescending(p => p.Id).Take(3);
            return PartialView(model);
        }
    }
}

FashionGo - full - Copy/FashionGo/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionGo.Controllers
{
    public class PagesController : BaseController
    {
        // GET: Pages
        //slug.html
        public ActionResult Index(string Slug)
        {
            var page = db.Pages.SingleOrDefault(p => p.Slug == Slug);
            if (page != null)
            {
                return View(page);
            }
            return RedirectToRoute("404");
        }

        //get siderbar
        public ActionResult _Sidebar()
        {
            ViewBag.MenuGioiThieu = db.Menus.Where(m => m.LocationId == 1).ToList();
            ViewBag.MenuTroGiup = db.Menus.Where(m => m.LocationId == 2).ToList();

            return PartialView();
        }
    }
}

FashionGo - full - Copy/FashionGo/Views/Shared/_AccountLayout.cshtml
@using System.Web.Configuration
<!DOCTYPE html>
<html lang="vi-Vn" dir="ltr" class='com_users view-registration j34 mm-hover no-touch'>
<head>
    <base href="@WebConfigurationManager.AppSettings["SiteUrl"].ToString()" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="generator" content="FashionGo - Thời trang đầm, váy, áo thun, áo khoác...!" />
    <link href="~/Content/images/favicon-fashiongo.png" rel="shortcut icon" type="image/vnd.microsoft.icon" />

    <title>@Html.Raw(ViewBag.Title)</title>

    @RenderSection("HeaderMetas", false)

    @Styles.Render("~/Assets/Frontend/FashionPro")
    @Styles.Render("~/Content/style")

    @Scripts.Render("~/Assets/Frontend/jquery")
    @RenderSection("HeaderScripts", false)

    @Html.Partial("Partials/_HeaderScripts")

</head>

<body class="bd">
    <div class="t3-wrapper">
        <!-- HEADER -->
        @Html.Action("Header", "Home")

        @{ Html.RenderPartial("_Alerts"); }

        <div id="t3-mainbody" class="container t3-mainbody">
            <div class="row">
                <!-- MAIN CONTENT -->
                <div id="t3-content" class="t3-content col-xs-12">
                    @RenderBody()
                </div>
            </div>
        </div>
        <!-- FOOTER -->
        @Html.Action("Footer", "Home")
        <!-- //FOOTER -->
        @Html.Partial("Partials/_ScrollToTop")
    </div>
</body>
@Scripts.Render("~/BootstrapValidator/jquery")
@RenderSection("Scripts", false)
</html>

FashionGo - full - Copy/FashionGo/Views/Shared/_Alerts.cshtml
@using Commons.Libs
@{
    var alerts = TempData.ContainsKey(Alert.TempDataKey)
                ? (List<Alert>)TempData[Alert.TempDataKey]
                : new List<Alert>();

    if (alerts.Any())
    {
        var count = 0;

        foreach (var alert in alerts)
        {
            count++;
            var dismissableClass = alert.Dismissable ? "alert-dismissable" : null;
            <div class="alert alert-@alert.AlertStyle @dismissableClass" aria-hidden="true" id="alert-@count">

                @if (alert.Dismissable)
                {
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                }
                @Html.Raw(alert.Message)
            </div>
        }

    }
}

FashionGo - full - Copy/FashionGo/Views/Shared/_BlogLayout.cshtml
@using System.Web.Configuration
<!DOCTYPE html>
<html lang="vi-Vn" dir="ltr" class='com_content view-category layout-blog itemid-196 j34 mm-hover no-touch'>
<head>
    <base href="@WebConfigurationManager.AppSettings["SiteUrl"].ToString()" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="generator" content="FashionGo - Thời trang đầm, váy, áo thun, áo khoác...!" />
    <link href="~/Content/images/favicon-fashiongo.png" rel="shortcut icon" type="image/vnd.microsoft.icon" />

    <title>@Html.Raw(ViewBag.Title)</title>

    @RenderSection("HeaderMetas", false)

    @Styles.Render("~/Assets/Frontend/FashionPro")
    @Styles.Render("~/Content/style")

    @Scripts.Render("~/Assets/Frontend/jquery")
    @RenderSection("HeaderScripts", false)

    @Html.Partial("Partials/_HeaderScripts")

</head>

<body class="bd">
    <div class="t3-wrapper">
        <!-- HEADER -->
        @Html.Action("Header", "Home")

        @{ Html.RenderPartial("_Alerts"); }

        <div id="t3-mainbody" class="container t3-mainbody">
            <div class="row">
                <!-- MAIN CONTENT -->
                <div id="t3-content" class="t3-content col-xs-12 col-sm-8  col-md-9">
                    @RenderBody()
                </div>
                <div class="t3-sidebar t3-sidebar-right col-xs-12 col-sm-4  col-md-3">
                    @Html.Action("_Sidebar", "Blogs")
                </div>
            </div>
        </div>
        <!-- FOOTER -->
        @Html.Action("Footer", "Home")
        <!-- //FOOTER -->
        @Html.Partial("Partials/_ScrollToTop")
    </div>
</body>
@Scripts.Render("~/BootstrapValidator/jquery")
@RenderSection("Scripts", false)
</html>

FashionGo - full - Copy/FashionGo/Views/Shared/_ClearLayout.cshtml
@using System.Web.Configuration
<!DOCTYPE html>
<html lang="vi-Vn" dir="ltr" class='com_users view-registration j34 mm-hover no-touch'>
<head>
    <base href="@WebConfigurationManager.AppSettings["SiteUrl"].ToString()" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="generator" content="FashionGo - Thời trang đầm, váy, áo thun, áo khoác...!" />
    <link href="~/Content/images/favicon-fashiongo.png" rel="shortcut icon" type="image/vnd.microsoft.icon" />

    <title>@Html.Raw(ViewBag.Title)</title>

    @RenderSection("HeaderMetas", false)

    @Styles.Render("~/Assets/Frontend/FashionPro")
    @Styles.Render("~/Content/style")

    @Scripts.Render("~/Assets/Frontend/jquery")
    @RenderSection("HeaderScripts", false)

    @Html.Partial("Partials/_HeaderScripts")

</head>

<body class="bd">
    <div class="t3-wrapper">
        <!-- HEADER -->
        @Html.Action("Header", "Home")

        @{ Html.RenderPartial("_Alerts"); }

        <div id="t3-mainbody" class="container t3-mainbody">
            <div class="row">
                <!-- MAIN CONTENT -->
                <div id="t3-content" class="t3-content col-xs-12">
                    @RenderBody()
                </div>
            </div>
        </div>
        <!-- FOOTER -->
        @Html.Action("Footer", "Home")
        <!-- //FOOTER -->
        @Html.Partial("Partials/_ScrollToTop")
    </div>
</body>
@Scripts.Render("~/BootstrapValidator/jquery")
@RenderSection("Scripts", false)
</html>

FashionGo - full - Copy/FashionGo/Views/Shared/_HomeLayout.cshtml
@using System.Web.Configuration
<!DOCTYPE html>
<html lang="vi-Vn" dir="ltr" class='com_eshop view-frontpage itemid-101 home j34 mm-hover'>
<head>
    <base href="@WebConfigurationManager.AppSettings["SiteUrl"].ToString()"/>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="generator" content="FashionGo - Thời trang đầm, váy, áo thun, áo khoác...!" />
    <link href="~/Content/images/favicon-fashiongo.png" rel="shortcut icon" type="image/vnd.microsoft.icon" />

    <title>@Html.Raw(ViewBag.Title)</title>

    @RenderSection("HeaderMetas", false)

    @Styles.Render("~/Assets/Frontend/FashionPro")
    @Styles.Render("~/Content/style")

    @Scripts.Render("~/Assets/Frontend/jquery")

    @RenderSection("HeaderScripts", false)

    @Html.Partial("Partials/_HeaderScripts")

</head>

<body class="bd">
    <div class="t3-wrapper">
        <!-- HEADER -->
        @Html.Action("Header", "Home")

        <!-- slideshow -->
        @Html.Action("_SliderShow", "Home")

        @{ Html.RenderPartial("_Alerts"); }

        @RenderBody()

        <!-- FOOTER -->
        @Html.Action("Footer", "Home")
        <!-- //FOOTER -->
        @Html.Partial("Partials/_ScrollToTop")
    </div>
</body>
@Scripts.Render("~/BootstrapValidator/jquery")
@RenderSection("Scripts", false)
</html>

FashionGo - full - Copy/FashionGo/Views/Shared/_LayouDetail.cshtml
@using System.Web.Configuration
<!DOCTYPE html>
<html lang="vi-Vn" dir="ltr" class='com_eshop view-category itemid-144 j34 mm-hover no-touch'>
<head>
    <base href="@WebConfigurationManager.AppSettings["SiteUrl"].ToString()" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="generator" content="FashionGo - Thời trang đầm, váy, áo thun, áo khoác...!" />
    <link href="~/Content/images/favicon-fashiongo.png" rel="shortcut icon" type="image/vnd.microsoft.icon" />

    <title>@Html.Raw(ViewBag.Title)</title>

    @RenderSection("HeaderMetas", false)

    @Styles.Render("~/Assets/Frontend/FashionPro")
    @Styles.Render("~/Content/style")

    @Scripts.Render("~/Assets/Frontend/jquery")
    @RenderSection("HeaderScripts", false)

    @Html.Partial("Partials/_HeaderScripts")

</head>

<body class="bd">
    <div class="t3-wrapper">
        <!-- HEADER -->
        @Html.Action("Header", "Home")

        @{ Html.RenderPartial("_Alerts"); }

        <div id="t3-mainbody" class="container t3-mainbody">
            <div class="row">
                <!-- MAIN CONTENT -->
                <div id="t3-content" class="t3-content col-xs-12 col-sm-8 col-md-9">
                    @RenderBody()
                </div>
                <div class="t3-sidebar t3-sidebar-right col-xs-12 col-sm-4 col-md-3">
                    @Html.Action("_SidebarDetails", "Product")
                </div>
            </div>
        </div>
        <!-- FOOTER -->
        @Html.Action("Footer", "Home")
        <!-- //FOOTER -->
        @Html.Partial("Partials/_ScrollToTop")
    </div>
</body>
@Scripts.Render("~/BootstrapValidator/jquery")
@RenderSection("Scripts", false)
</html>

FashionGo - full - Copy/FashionGo/Views/Shared/_Layout.cshtml
@using System.Web.Configuration
<!DOCTYPE html>
<html lang="vi-Vn" dir="ltr" class='com_eshop view-category itemid-144 j34 mm-hover no-touch'>
<head>
    <base href="@WebConfigurationManager.AppSettings["SiteUrl"].ToString()" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="generator" content="FashionGo - Thời trang đầm, váy, áo thun, áo khoác...!" />
    <link href="~/Content/images/favicon-fashiongo.png" rel="shortcut icon" type="image/vnd.microsoft.icon" />

    <title>@Html.Raw(ViewBag.Title)</title>

    @RenderSection("HeaderMetas", false)

    @Styles.Render("~/Assets/Frontend/FashionPro")
    @Styles.Render("~/Content/style")

    @Scripts.Render("~/Assets/Frontend/jquery")
    @RenderSection("HeaderScripts", false)

    @Html.Partial("Partials/_HeaderScripts")

</head>

<body class="bd">
    <div class="t3-wrapper">
        <!-- HEADER -->
        @Html.Action("Header", "Home")

        @{ Html.RenderPartial("_Alerts"); }

        <div id="t3-mainbody" class="container t3-mainbody">
            <div class="row">
                <!-- MAIN CONTENT -->
                <div id="t3-content" class="t3-content col-xs-12 col-sm-8 col-sm-push-4 col-md-9 col-md-push-3">
                    @RenderBody()
                </div>
                <div class="t3-sidebar t3-sidebar-left col-xs-12 col-sm-4 col-sm-pull-8 col-md-3 col-md-pull-9 ">
                    @Html.Action("_Sidebar", "Product")
                </div>
            </div>
        </div>
        <!-- FOOTER -->
        @Html.Action("Footer", "Home")
        <!-- //FOOTER -->
        @Html.Partial("Partials/_ScrollToTop")
    </div>
</body>
@Scripts.Render("~/BootstrapValidator/jquery")
@RenderSection("Scripts", false)
</html>

FashionGo - full - Copy/FashionGo/Views/Shared/_PageLayout.cshtml
@using System.Web.Configuration
<!DOCTYPE html>
<html lang="vi-Vn" dir="ltr" class='com_content view-article itemid-111 j34 mm-hover'>
<head>
    <base href="@WebConfigurationManager.AppSettings["SiteUrl"].ToString()" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="generator" content="FashionGo - Thời trang đầm, váy, áo thun, áo khoác...!" />
    <link href="~/Content/images/favicon-fashiongo.png" rel="shortcut icon" type="image/vnd.microsoft.icon" />

    <title>@Html.Raw(ViewBag.Title)</title>

    @RenderSection("HeaderMetas", false)

    @Styles.Render("~/Assets/Frontend/FashionPro")
    @Styles.Render("~/Content/style")

    @Scripts.Render("~/Assets/Frontend/jquery")
    @RenderSection("HeaderScripts", false)

    @Html.Partial("Partials/_HeaderScripts")
    
</head>

<body class="bd">
    
    <div class="t3-wrapper">
        <!-- HEADER -->
        @Html.Action("Header", "Home")

        @{ Html.RenderPartial("_Alerts"); }

        <div id="t3-mainbody" class="container t3-mainbody">
            <div class="row">
                <!-- MAIN CONTENT -->
                <div id="t3-content" class="t3-content col-xs-12 col-sm-8  col-md-9">
                    @RenderBody()
                </div>
                <div class="t3-sidebar t3-sidebar-right col-xs-12 col-sm-4  col-md-3">
                    @Html.Action("_Sidebar", "Pages")
                </div>
            </div>
        </div>
        <!-- FOOTER -->
        @Html.Action("Footer", "Home")
        <!-- //FOOTER -->
        @Html.Partial("Partials/_ScrollToTop")
    </div>

</body>
@Scripts.Render("~/BootstrapValidator/jquery")
@RenderSection("Scripts", false)
</html>