FashionGo - full - Copy/FashionGo/Models/Entities/Testimonial.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FashionGo.Models.Entities
{
    public partial class Testimonial
    {
        public int Id { get; set; }

        [Column(TypeName = "nText")]
        public string Message { get; set; }

        public string CustomerName { get; set; }

        public string CustomerAvatar { get; set; }
    }
}

FashionGo - full - Copy/FashionGo/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionGo.Areas.Admin.Controllers
{
    public class HomeController : AdminController
    {
        // GET: admin/Default
        public ActionResult Index()
        {
            ViewBag.NewOrders = db.Orders.OrderByDescending(o => o.Id).Take(8).ToList();
            ViewBag.CountOrder = db.Orders.Count();
            ViewBag.CountProduct = db.Products.Count();
            ViewBag.CountUsers = db.Users.Count();

            var model = db.Products.OrderByDescending(p => p.Id).Take(5).ToList();
            return View(model);
        }

        public ActionResult Header()
        {
            ViewBag.Orders = db.Orders.Where(p => p.StatusId == 1).ToList();

            return PartialView("_Header");
        }
        Double CurentMoth(int IdStatust)
        {
            var Orders = db.Orders.Where(o => o.OrderDate.Value.Month == DateTime.Now.Month
                                            && o.OrderStatus.Id == IdStatust

            ).ToList();
            Double? count = 0;
            foreach (var item in Orders)
            {
                if (item.TotalOrder > 0)
                {
                    count += item.TotalOrder == null ? 0 : item.TotalOrder;
                }
            }
            return   Convert.ToDouble(count);
        }
    }
}

FashionGo - full - Copy/FashionGo/Areas/Admin/Controllers/TestimonialsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FashionGo.Models;
using FashionGo.Models.Entities;

namespace FashionGo.Areas.Admin.Controllers
{
    public class TestimonialsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Admin/Testimonials
        public ActionResult Index()
        {
            return View(db.Testimonials.ToList());
        }

        // GET: Admin/Testimonials/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Testimonial testimonial = db.Testimonials.Find(id);
            if (testimonial == null)
            {
                return HttpNotFound();
            }
            return View(testimonial);
        }

        // GET: Admin/Testimonials/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Testimonials/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Message,CustomerName,CustomerAvatar")] Testimonial testimonial)
        {
            if (ModelState.IsValid)
            {
                db.Testimonials.Add(testimonial);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(testimonial);
        }

        // GET: Admin/Testimonials/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Testimonial testimonial = db.Testimonials.Find(id);
            if (testimonial == null)
            {
                return HttpNotFound();
            }
            return View(testimonial);
        }

        // POST: Admin/Testimonials/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Message,CustomerName,CustomerAvatar")] Testimonial testimonial)
        {
            if (ModelState.IsValid)
            {
                db.Entry(testimonial).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(testimonial);
        }

        // GET: Admin/Testimonials/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Testimonial testimonial = db.Testimonials.Find(id);
            if (testimonial == null)
            {
                return HttpNotFound();
            }
            return View(testimonial);
        }

        // POST: Admin/Testimonials/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Testimonial testimonial = db.Testimonials.Find(id);
            db.Testimonials.Remove(testimonial);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FashionGo - full - Copy/FashionGo/Controllers/BannerAdsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionGo.Controllers
{
    public class BannerAdsController : Controller
    {
        // GET: BannerAds
        public ActionResult _HomeBanner()
        {
            return PartialView();
        }
    }
}

FashionGo - full - Copy/FashionGo/Controllers/BlogsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionGo.Controllers
{
    public class BlogsController : BaseController
    {
        
        // GET: Blogs
        public ActionResult Index(int? page)
        {
            int pageNumber = (page ?? 1);
            var pageSize = 8;
            var model = db.Posts.Where(p => p.Active == true).OrderByDescending(p => p.createDate).ToList();
            return View(model.ToPagedList(pageNumber, pageSize));
        }
        

        // GET: Category
        public ActionResult Category(string Slug, int? page)
        {
            int pageNumber = (page ?? 1);
            var pageSize = 8;

            var Cat = db.Categories.SingleOrDefault(c => c.Slug == Slug);
            if (Cat == null)
            {
                return RedirectToRoute("404");
            }

            var model = Cat.Posts.OrderByDescending(p => p.createDate).Where(p => p.Active == true).ToList();
            ViewBag.Cat = Cat;
            return View(model.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult ShowPost(string Slug)
        {
            var Post = db.Posts.SingleOrDefault(p => p.Slug == Slug);

            if (Post == null)
            {
                return RedirectToRoute("404");
            }

            ViewBag.RelatedPosts = db.Posts.Where(p => p.CatId == Post.CatId).Where(p => p.Id != Post.Id).Take(4).ToList();
            ViewBag.Cat = Post.Category;

            return View(Post);
        }

        //get siderbar
        public ActionResult _Sidebar()
        {
            ViewBag.Cats = db.Categories.ToList();
            var PopularPosts = db.Posts.OrderByDescending(p => p.createDate).Where(p => p.Active == true).Take(5);
            return PartialView(PopularPosts);
        }

        public ActionResult _LastNews()
        {
            var model = db.Posts.Where(p => p.Active == true).OrderByDescending(p => p.Id).Take(3);
            return PartialView(model);
        }
    }
}

FashionGo - full - Copy/FashionGo/Controllers/BrandController.cs
using System.Linq;
using System.Web.Mvc;

namespace FashionGo.Controllers
{
    public class BrandController : BaseController
    {
        // GET: Brand
       
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ListBrand()
        {
            var model = db.Manufacts.ToList();
            return PartialView("Partials/_Brand", model);
        }

        public ActionResult _Manufactures()
        {
            return PartialView();
        }
    }
}

FashionGo - full - Copy/FashionGo/Controllers/HomeController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using FashionGo.Models.Entities;
using FashionGo.Models;

namespace FashionGo.Controllers
{
    public class HomeController : BaseController
    {
        public DateTime now = new DateTime();

        public ActionResult Index()
        {
            //Saleoff product
            var saleOffProducts = db.Products.Where(p=>p.Actived == true).Where(p => p.IsSpecial == true).Take(20);
            ViewBag.saleOffProducts = saleOffProducts;

            //Lastest Product
            var lastProducts = db.Products.Where(p => p.Actived == true).OrderByDescending(p=>p.IsNew).OrderBy(p => p.CreateDate).Take(20);
            ViewBag.lastProducts = lastProducts;

            var model = db.ProductCategories.Where(c=>c.ParentId == null).OrderBy(c=>c.DisplayOrder);

            return View(model);
        }

        
        public ActionResult _AboutUs()
        {
            return PartialView();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Liên hệ FashionGo";

            return View();
        }

        public ActionResult Category()
        {
            var model = db.ProductCategories.OrderBy(p => p.DisplayOrder);
            return PartialView("Partials/_Category", model);
        }

        public ActionResult Header()
        {
            var today = new DateTime();
            var cart = ShoppingCart.Cart;
            try
            {
                var cats = db.ProductCategories.OrderBy(p => p.DisplayOrder).ToList();
                ViewBag.ProductCategories = cats;
            }
            catch
            {

            }

            try
            {
                // Lấy cookie cũ tên views
                var wishlist = Request.Cookies["wishlist"];
                // Nếu chưa có cookie cũ -> tạo mới
                if (wishlist == null)
                {
                    wishlist = new HttpCookie("wishlist");
                }
                ViewBag.Count = wishlist.Values.Count;
            }
            catch
            {

            }

            ViewBag.Provinces = db.Provinces.OrderBy(p => p.Name).ToList();

            ViewBag.BannerTop = db.Banners.Where(b => b.BannerTypeId == 1)
                                        .Where(b => b.BannerPositionId == 1)
                                        .Where(b => b.Active == true)
                                        .Where(b => b.StartDate >= today)
                                        .Where(b => b.EndDate > today).FirstOrDefault();

            return PartialView("Partials/_Header", cart.Items);
        }

        public ActionResult _SliderShow()
        {
            var model = db.Sliders.OrderByDescending(s=>s.Id).Take(8).ToList();
            return PartialView(model);
        }

        public ActionResult _Testimonials()
        {
            var testimonials = db.Testimonials.Take(6).ToList();
            return PartialView(testimonials);
        }

        public ActionResult _AllShopCategory()
        {
            var productCategories = db.ProductCategories.Where(c => c.ParentId == null).Take(5).ToList();
            return PartialView(productCategories);
        }

        public ActionResult _TosWidget()
        {
            return PartialView();
        }


        public ActionResult Footer()
        {
            ViewBag.MenuGioiThieu = db.Menus.Where(m=>m.LocationId ==1).ToList();
            ViewBag.MenuTroGiup = db.Menus.Where(m => m.LocationId == 2).ToList();

            return PartialView("Partials/_Footer");
        }


        public ActionResult Culture(string id)
        {
            HttpCookie cookie = Request.Cookies["Culture"];
            if (cookie == null)
            {
                cookie = new HttpCookie("Culture", id);
            }
            cookie.Value = id;
            cookie.Expires = DateTime.Now.AddYears(1);
            Response.SetCookie(cookie);

            return Redirect("/");
        }

        public ActionResult PopoupBanner()
        {
            //var today = new DateTime();
            Banner popup = db.Banners.Where(b => b.BannerTypeId == 2)
                            .Where(b => b.Active == true).FirstOrDefault();

            return PartialView("Partials/_PopupBaner", popup);
        }


        public ActionResult NotFound()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AjaxGetDistrictByProvice(string provinceId)
        {
            //var m = db.Provinces.Find(provinceId);
            return PartialView(db.Districts.Where(d => d.ProvinceId == provinceId).ToList());
        }

    }
}

FashionGo - full - Copy/FashionGo/Views/Home/AjaxGetDistrictByProvice.cshtml
@model IEnumerable<FashionGo.Models.Entities.District>

@foreach (var item in Model) {
    <option value="@item.DistrictId">@item.Type @item.Name</option>
}

FashionGo - full - Copy/FashionGo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FashionGo - full - Copy/FashionGo/Views/Home/Index.cshtml
@using FashionGo.Models.Entities
@using FashionGo.Models.Dao
@using System.Web.Configuration

@model IEnumerable<FashionGo.Models.Entities.ProductCategory>

@{

    ViewBag.Title = Html.Raw(WebConfigurationManager.AppSettings["SiteName"].ToString() + " - " +  WebConfigurationManager.AppSettings["SiteSlogan"].ToString());
    Layout = "~/Views/Shared/_HomeLayout.cshtml";

    Random rd = new Random();
}

@section HeaderMetas{
    <meta name="description" content="@Html.Raw(WebConfigurationManager.AppSettings["Description"].ToString())">
    <meta name="keywords" content="@Html.Raw(WebConfigurationManager.AppSettings["Keywords"].ToString())">
    <meta name="author" content="@Html.Raw(WebConfigurationManager.AppSettings["SiteName"].ToString())">

    <meta property="og:url" content="@Request.Url" />
    <meta property="og:title" content="@ViewBag.Title" />
    <meta property="og:description" content="@Html.Raw(WebConfigurationManager.AppSettings["Description"].ToString())" />
}

<!-- Wellcome block -->
@Html.Action("_AboutUs", "Home")

<!-- featured-product -->
@Html.Action("_FeaturedProducts", "Product")
<!-- //featured-product -->


<!-- SPOTLIGHT 1 -->
@Html.Action("_HomeBanner", "BannerAds")
<!-- //SPOTLIGHT 1 -->


<!-- latest-product -->
@Html.Action("_LastestProducts", "Product")
<!-- //latest-product -->
<!-- testimonial -->
@Html.Action("_Testimonials")
<!-- //testimonial -->
<!-- shop-by-cat -->
@Html.Action("_AllShopCategory", "Home")
<!-- //shop-by-cat -->
<!-- shipping -->
@Html.Action("_TosWidget", "Home")
<!-- //shipping -->
<!-- eshop-products -->
<div class="container t3-sl eshop-products">
    <!-- SPOTLIGHT -->
    <div class="t3-spotlight t3-eshop-products  row">
        <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
            @Html.Action("_BestSalerProducts", "Product")
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
            @Html.Action("_DiscountProducts", "Product")
        </div>
    </div>
    <!-- SPOTLIGHT -->
</div>
<!-- //eshop-products -->
<!-- container -->
@Html.Action("_Manufactures", "Brand")
<!-- //container -->
<!-- blog -->
@Html.Action("_LastNews", "Blogs")
<!-- //blog -->

FashionGo - full - Copy/FashionGo/Views/Home/NotFound.cshtml
@{
    ViewBag.Title = "Trang không tồn tại";
}

<div class="x-page inner-bottom-sm">
    <div class="row">
        <div class="col-md-12 x-text text-center">
            <h1>404</h1>
            <p>Chúng tôi không tìm thấy trang bạn yêu cầu, xin thứ lỗi vì sự bất tiện này. </p>
            <form role="form" class="outer-top-vs outer-bottom-xs">
                <input placeholder="Search" autocomplete="off">
                <button class="btn-default le-button">Tìm</button>
            </form>
            <a href="home.html"><i class="fa fa-home"></i> Về trang chủ</a>
        </div>
    </div><!-- /.row -->
</div>

FashionGo - full - Copy/FashionGo/Views/Home/_AboutUs.cshtml
<div id="t3-mainbody" class="container t3-mainbody">
    <div class="row">
        <!-- MAIN CONTENT -->
        <div id="t3-content" class="t3-content col-xs-12">
            <div id="system-message-container">
            </div>

            <div class="eshop-shop-introduction">
                <h1 style="text-align: center;">CHÀO MỪNG!</h1>
                <h2 style="text-align: center;">ĐẾN VỚI FASHIONGO</h2>
                <p style="text-align: center;">Với mục tiêu tạo ra những trải nghiệm mua sắm thời trang trực tuyến tuyệt vời, FashionGo (FG) ra đời và luôn nỗ lực để mang đến khách hàng mua sắm thời trang: Kho thời trang chất lượng, Giá cả cạnh tranh, Dịch vụ chăm sóc khách hàng tận tâm... và hơn thế chung tôi luôn cam kết bằng hành động của mình. Chúc bạn lựa chọn được phong cách phù hợp với mình cùng FG!</p>
                <p style="text-align: center;"><a class="btn btn-primary" href="@Url.RouteUrl("PageDetails", new { Slug = "gioi-thieu-ve-fashiongo" })" title="Giới thiệu về FashionGo">Đọc thêm</a></p>
            </div>

        </div>
        <!-- //MAIN CONTENT -->
    </div>
</div>

FashionGo - full - Copy/FashionGo/Views/Home/_AllShopCategory.cshtml
@model IEnumerable<FashionGo.Models.Entities.ProductCategory>
@using System.Web.Configuration
@using FashionGo.Models.Dao

<nav class="wrap t3-shop-by-cat ">
    <div class="container">
        <div class="t3-module module " id="Mod98">
            <div class="module-inner">
                <h3 class="module-title "><span>Danh mục sản phẩm</span></h3><div class="module-ct">
                    <div class="eshop-product-tabs">
                        <div class="row-fluid">
                            <div class="span12">
                                <div class="tabbable default">
                                    <ul class="nav nav-pills nav-stacked" id="productTab">
                                        @{ 
                                            var rel = 0;
                                            var data = 66;
                                        }
                                        @foreach (var cat in Model)
                                        {
                                            var activeClass = rel == 0 ? "active" : "";

                                            <li class="@activeClass"><a href="#category-tab-@rel@data" rel="@rel" data="@data" data-toggle="tab">@cat.Name</a></li>

                                            rel++;
                                        }
                                    </ul>
                                    <div class="tab-content" id="productContent">
                                        @{
                                            rel = 0;
                                        }
                                        @foreach (var cat in Model)
                                        {
                                            var activeClass = rel == 0 ? "active" : "";
                                            <input type="hidden" id="setcount-@rel" name="setcount-@rel" value="0" />
                                            <div class="tab-pane @activeClass row-fluid" id="category-tab-@rel@data">
                                                <div class="category-desc span3">
                                                    <p>@Html.Raw(cat.Description)</p>											
                                                    <div class="category-view-all">
                                                        <a class="btn btn-primary" href="@Url.RouteUrl("ProductCategory", new { slug = cat.Name.ToAscii(), id = cat.CatId })" title="Xem danh mục @cat.Name">
                                                            Xem thêm...
                                                        </a>
                                                    </div>
                                                </div>
                                                <div class="clearfix span9">
                                                    <ul id="item-container-@rel@data" class="product-tab-content row ">
                                                        @foreach (var item in cat.AllProducts(18))
                                                        {
                                                            <li class="eshop-product-tab col-lg-4 col-md-4 col-xs-col-md-4">
                                                                <div class="image">
                                                                    <a href="@Url.RouteUrl("ProductDetails", new { slug = item.Name.ToAscii(), id = item.Id })" title="@item.Name">
                                                                        <img class="image img-responsive" alt="@item.Name" src="@item.FeaturedImage">
                                                                    </a>
                                                                </div>
                                                                <h4 class="eshop-product-title">
                                                                    <a href="@Url.RouteUrl("ProductDetails", new { slug = item.Name.ToAscii(), id = item.Id })" class="link" data-original-title="@item.Name">
                                                                        @item.Name
                                                                    </a>
                                                                </h4>
                                                                <div class="row">
                                                                    <div class="col-lg-6 col-md-6 col-xs-6">
                                                                        @if (item.Discount!= null&& item.Discount.Value > 0)
                                                                        {
                                                                            <span class="eshop-base-price">@Html.FormatValue(item.Price, "{0:0,0}")đ</span>
                                                                        }
                                                                        <span class="eshop-price">@Html.FormatValue(item.PriceAfter, "{0:0,0}")đ</span>
                                                                    </div>
                                                                    <div class="col-lg-6 col-md-6 col-xs-6">
                                                                        <button id="add-to-cart-@item.Id" class="btn btn-primary" onclick="flyToCart(@item.Id); ">Thêm vào giỏ</button>
                                                                    </div>
                                                                </div>
                                                            </li>
                                                        }
                                                    </ul>
                                                </div>
                                                <div class="clearfix"></div>
                                                <div class="pagination pagination-toolbar" style="text-align: center; margin-top: 20px;">
                                                    <ul class="pagination-list-@rel@data"></ul>
                                                </div>
                                            </div>
                                            rel++;
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <script type="text/javascript">
                            jQuery(function ($) {
                                $(document).ready(function () {
                                    loadPagination(0, @data);
                                    $('#setcount-0').attr('value', 1);
                                });
                                $("ul#productTab li a").on('shown.bs.tab', function (e) {
                                    var hClass = $('#productContent div').hasClass('active');
                                    if (hClass) {
                                        $('#productContent div').removeClass('animated bounceInUp');
                                    }
                                    var getCountData = $(this).attr('rel');
                                    var getModuleId = $(this).attr('data');
                                    if ($('#setcount-' + getCountData).val() != 1) {
                                        loadPagination(getCountData, getModuleId);
                                        $('#setcount-' + getCountData).val(1);
                                    }
                                    $('#category-tab-' + getCountData + getModuleId).addClass('animated bounceInUp')
                                });
                                loadPagination = (function (countData, moduleId) {
                                    $("ul.pagination-list-" + countData + moduleId).eshopPagination({
                                        containerID: "item-container-" + countData + moduleId,
                                        first: "First",
                                        last: "Last",
                                        perPage: 3,
                                        keyBrowse: true,
                                        pause: 0,
                                        clickStop: true,
                                        scrollBrowse: false,
                                        animation: "bounceIn",
                                    });
                                })

                            })
                    </script>
                </div>
            </div>
        </div>
    </div>
</nav>

FashionGo - full - Copy/FashionGo/Views/Home/_SliderShow.cshtml
@model IEnumerable<FashionGo.Models.Entities.Slider>

<nav class="wrap t3-slideshow ">
    <div class="inner">
        <div id="sp-smart-slider" class="sp-smart-slider sp-awetive-layout  ">

            <div class="sp-slider-items">

                <div class="sp-slider-item odd animate-in ">
                    <div class="sp-slider-image" style="background-image: url('http://eshoptemplates.com/fashionpro/images/sampledata/slideshow/sl-1.jpg');"></div>

                    <div class="container">
                        <div class="sp-slider-content">


                            <h1 class="sp-title sp-animation-1">
                                New
                            </h1>

                            <h2 class="sp-posttitle sp-animation-2">
                                Collection
                            </h2>


                            <p class="sp-introtext sp-animation-3">

                                Autumn 2018
                            </p>



                            <div class="clearfix"></div>


                            <a class="btn btn-primary" href="#" class="btn-more sp-animation-5">
                                Shop Now
                            </a>


                            <div class="clearfix"></div>

                        </div><!--/.sp-slider-content-->
                    </div>
                </div><!--/.slider-item-->

                <div class="sp-slider-item even  ">
                    <div class="sp-slider-image" style="background-image: url('http://eshoptemplates.com/fashionpro/images/sampledata/slideshow/sl-2.jpg');"></div>

                    <div class="container">
                        <div class="sp-slider-content">


                            <h1 class="sp-title sp-animation-1">
                                Sale
                            </h1>

                            <h2 class="sp-posttitle sp-animation-2">
                                get up to
                            </h2>


                            <p class="sp-introtext sp-animation-3">

                                50%
                            </p>


                            <div class="sp-full-text sp-animation-4">
                                off
                            </div>



                            <div class="clearfix"></div>




                            <div class="clearfix"></div>

                        </div><!--/.sp-slider-content-->
                    </div>
                </div><!--/.slider-item-->

                <div class="sp-slider-item odd  ">
                    <div class="sp-slider-image" style="background-image: url('http://eshoptemplates.com/fashionpro/images/sampledata/slideshow/sl-3.jpg');"></div>

                    <div class="container">
                        <div class="sp-slider-content">


                            <h1 class="sp-title sp-animation-1">
                                Dress
                            </h1>

                            <h2 class="sp-posttitle sp-animation-2">
                                Collection
                            </h2>


                            <p class="sp-introtext sp-animation-3">

                                2018
                            </p>





                            <div class="clearfix"></div>


                            <a class="btn btn-primary" href="#" class="btn-more sp-animation-5">
                                Shop Now
                            </a>

                            <div class="clearfix"></div>

                        </div><!--/.sp-slider-content-->
                    </div>
                </div><!--/.slider-item-->
            </div><!--/.slider-items-->
            <ol class="slide-indicators">
                <li class="active">
                    <span class="text-hide">show</span>
                <li class="">
                    <span class="text-hide">show</span>
                <li class="">
                    <span class="text-hide">show</span>
            </ol>
        </div>
    </div>
</nav>
<!-- //slideshow -->